version: "3.8"
services:
  hangman:
    build: .
    # stdin_open: true
    # tty: true
    volumes:
      - .:/hangman

  test:
    build:
      context: .
      dockerfile: pytest.dockerfile
    volumes:
      - .:/hangman
    command: pytest
